### ISSUE TITLE
Data matrix - genes*clusters

### ISSUE THREAD

**Issue by ZhenyaoYe** [AllenInstitute/dLGN_cross_species#1]
Hi Allen Institute, 

Thank you for providing the source codes. I have a question regarding the identified clusters for each species.

Once the clusters are identified, I'm wondering if there's a way to obtain a data matrix that represents genes * clusters, rather than genes * single cells? 

Thank you in advance! 

Best regards,
Zhenyao

**Comment by cvanvelt** [comment]
Hi Zhenyao,

the easiest way to do it would be using the scrattch.hicat package. It has a function to calculate, for example, the mean gene expression per cluster uisng the "get_cl_means_" function.

Example:
```
# mat is A gene (rows) x samples (columns) sparse matrix
# cl is a cluster factor object

cl = factor(setNames(anno$cluster_id, anno$sample_name))
scrattch.hicat::get_cl_means(mat, cl)
```

Hope this helps.
Cindy

**Comment by ZhenyaoYe** [comment]
Hi Cindy, 

Thank you for your prompt response! It is really helpful! 

Best regards,
Zhenyao
